name: doctor_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  velocity_x: ^4.1.2
  get: ^4.6.6
  cupertino_icons: ^1.0.6
  firebase_core: ^2.25.4
  firebase_auth: ^4.11.1
  cloud_firestore: ^4.15.4
 # Adjust the version as needed

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - pictures/icons/
    - pictures/images/
  fonts:
    - family: nunito
      fonts:
        - asset: fonts/nunito-bold.ttf
          style: italic
